#!/usr/bin/env python3
"""Write maps/skog.txt: a 50x32 forest with a winding path, trees kept off the path."""
import os, random
W, H = 50, 32
rng = random.Random(7)
grid = [["." for _ in range(W)] for _ in range(H)]
for y in range(H):
    for x in range(W):
        if x < 2 or x >= W - 2 or y < 2 or y >= H - 2:
            grid[y][x] = "#"
# path: west edge (rows 16-17) -> clearing -> north-east and south-east branches
path = set()
def line(x0, y0, x1, y1, w=2):
    x, y = x0, y0
    while (x, y) != (x1, y1):
        for dx in range(w):
            for dy in range(w):
                path.add((x + dx, y + dy))
        if x != x1: x += 1 if x1 > x else -1
        elif y != y1: y += 1 if y1 > y else -1
    for dx in range(w):
        for dy in range(w):
            path.add((x + dx, y + dy))
line(2, 16, 12, 16); line(12, 16, 12, 11); line(12, 11, 22, 11); line(22, 11, 22, 8); line(22, 8, 36, 8)
line(36, 8, 36, 5); line(36, 5, 44, 5)                     # north-east branch -> chest
line(22, 11, 26, 11); line(26, 11, 26, 20); line(26, 20, 40, 20); line(40, 20, 40, 26); line(40, 26, 46, 26)  # south-east
line(12, 16, 12, 22); line(12, 22, 18, 22)                  # south spur -> chest
for (x, y) in path:
    if 2 <= x < W - 2 and 2 <= y < H - 2:
        grid[y][x] = ":"
clear = set()
for (x, y) in path:
    for dx in (-1, 0, 1):
        for dy in (-1, 0, 1):
            clear.add((x + dx, y + dy))
# clearing around the hunter and the chests
for cx, cy, r in [(30, 9, 3), (44, 6, 2), (18, 21, 2), (47, 27, 2)]:
    for x in range(cx - r, cx + r + 1):
        for y in range(cy - r, cy + r + 1):
            clear.add((x, y))
for y in range(2, H - 2):
    for x in range(2, W - 2):
        if grid[y][x] != "." or (x, y) in clear:
            continue
        r = rng.random()
        if x % 4 == 1 and y % 4 == 1 and r < 0.6:
            grid[y][x] = rng.choice("GNGNY")          # big trees on a sparse lattice
        elif (x + y) % 2 == 0 and r < 0.75:
            grid[y][x] = rng.choice("TTPPTPD")         # small trees on a checkerboard
        elif r < 0.18:
            grid[y][x] = rng.choice("BbhgfwF")
grid[17][4] = "@"   # test spawn (?map=skog); real entry is the west door
rows = ["".join(r) for r in grid]
objects = '''
map 0 0 music=forest base=grass light=cycle fx=leaves ambient=wind
door 2 16 id=vest to=landsby at=ost dir=right h=2
sign 5 15 text="Vestmarka skog.|Stien svinger. Ikke gå fra den om du vil hjem igjen."
npc 30 9 who=Hunter name="Jegeren" text="Sjø. Stille her, ikke sant?|Jeg så noe blinke lengst nordøst, bak de store trærne. Kan hende det bare var sola."
chest 45 6 id=kiste_skog_ne text="En pilspiss av flint. Skarp ennå."
chest 18 21 id=kiste_skog_s text="En liten treskje med en bjørn skåret inn i skaftet."
chest 47 27 id=kiste_skog_se text="Et stykke rav med et insekt inni."
'''
out = "// Skog — generated by tools/gen_forest.py (seed 7); edit the script, not this file.\n" + "\n".join(rows) + "\n" + objects
open(os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "maps", "skog.txt"), "w").write(out)
print("\n".join(rows))
